version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels: ["dependencies", "python"]
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels: ["dependencies", "javascript"]
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "docker"]

  - package-ecosystem: "docker"
    directory: "/web"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "docker"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "github-actions"]
